# Operaciones por capas

In [7]:
import tensorflow as tf
session = tf.Session()

AttributeError: module 'tensorflow' has no attribute 'Session'

- $X \in \mathbb R_{3\times 4}$

In [3]:
import numpy as np
my_array = np.array([[1.,3.,5.,7.],
                     [-2.,0.,7.,6.],
                     [-6.,-1.,0.,3.]])
my_array

array([[ 1.,  3.,  5.,  7.],
       [-2.,  0.,  7.,  6.],
       [-6., -1.,  0.,  3.]])

In [4]:
x_vals = np.array([my_array, my_array+1])
x_vals

array([[[ 1.,  3.,  5.,  7.],
        [-2.,  0.,  7.,  6.],
        [-6., -1.,  0.,  3.]],

       [[ 2.,  4.,  6.,  8.],
        [-1.,  1.,  8.,  7.],
        [-5.,  0.,  1.,  4.]]])

In [15]:
x_data = tf.placeholder(tf.float32, shape=(3,4))

- $m_1 \in \mathbb R^4$
- $m_2, a_1\in \mathbb R$

In [8]:
m1 = tf.constant([[1.], [0.], [-2.],[5.]])
m2 = tf.constant([[7.]])
a1 = tf.constant([[15.]])

$$[(X\cdot m_1)\cdot m_2]+a_1$$

In [13]:
prod1 = tf.matmul(x_data, m1)
prod2 = tf.matmul(prod1, m2)
add1 = tf.add(prod2, a1)

In [14]:
for x_val in x_vals:
    print(session.run(add1, feed_dict={x_data: x_val}))

[[197.]
 [113.]
 [ 78.]]
[[225.]
 [141.]
 [106.]]
