# Tensores y variables

In [1]:
import tensorflow as tf


$\vec{v} = (v_1, v_2, v_3,\cdots, v_n)\in \mathbb R^n$ es un tensor unidimensional (vector)

$ M = \begin{pmatrix} 
    1 & 2 & 3\\
    4 & 5 & 6
    \end{pmatrix} \in \mathbb R_{2\times 3}$ es un tensor bidimensional (matriz)

$ T \in \mathbb R_{n_1\times n_2\times \cdots \times n_k}$ es un tensor $k$-dimesional

##  Tensores fijos

In [2]:
zero_t = tf.zeros([3, 4, 6])
zero_t

<tf.Tensor: shape=(3, 4, 6), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]], dtype=float32)>

In [3]:
ones_t = tf.ones([3, 4])
ones_t

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [4]:
filled_t = tf.fill([4,5,2], 1988)
filled_t

<tf.Tensor: shape=(4, 5, 2), dtype=int32, numpy=
array([[[1988, 1988],
        [1988, 1988],
        [1988, 1988],
        [1988, 1988],
        [1988, 1988]],

       [[1988, 1988],
        [1988, 1988],
        [1988, 1988],
        [1988, 1988],
        [1988, 1988]],

       [[1988, 1988],
        [1988, 1988],
        [1988, 1988],
        [1988, 1988],
        [1988, 1988]],

       [[1988, 1988],
        [1988, 1988],
        [1988, 1988],
        [1988, 1988],
        [1988, 1988]]])>

In [5]:
cte_t = tf.constant([1,2,3,4,5])
cte_t

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5])>

## Tensores por tamaño

In [6]:
zero_sim = tf.zeros_like(cte_t)
zero_sim

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 0, 0, 0, 0])>

In [7]:
ones_sim = tf.ones_like(cte_t)
ones_sim

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 1, 1, 1, 1])>

## Tensor en forma de secuencia
- linspace()
- range()

In [8]:
sec_t = tf.linspace(start=0.0, stop = 1.0, num = 5)
sec_t

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0.  , 0.25, 0.5 , 0.75, 1.  ], dtype=float32)>

El resultado anterior sería el tensor $[0.0, 0.25, 0.5, 0.75, 1.0]$.

In [9]:
range_seq = tf.range(start=5.0, limit = 15.0, delta = 4.0)
range_seq

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 5.,  9., 13.], dtype=float32)>

El resultado anterior sería el tensor $[5, 9, 13]$.

## Tensores aleatorios

In [10]:
rand_unif_t = tf.random_uniform([3,4], minval=0, maxval=1)
rand_unif_t

AttributeError: module 'tensorflow' has no attribute 'random_uniform'

In [ ]:
rand_norm_t = tf.random_normal([3, 4], mean=0.0, stddev= 1.0)
rand_norm_t

In [ ]:
rand_trunc_normal_t = tf.truncated_normal([3,4], mean=0.0, stddev=1.0)
rand_trunc_normal_t

In [ ]:
tf.random_shuffle(rand_unif_t)

In [ ]:
tf.random_crop(rand_norm_t, [2,6])

# Variables

In [ ]:
tf.Variable(rand_norm_t)

In [ ]:
tf.convert_to_tensor(1988)

In [ ]:
tf.convert_to_tensor([1,2,3,4,5])

In [ ]:
filled_t

In [ ]:
zero_t2 = tf.zeros([3, 4, 6])


In [ ]:
zero_t2
